env: dev
port: 8080

postgres:
  dbname: lumino_dev
  host: pgm-2ze3795emd629opy-l9.pg.rds.aliyuncs.com
  port: 5432
  user: postgres
  passwd: Zmalqp78
  maxOpenConns: 50

oss:
  bucket: lumino-dev
  region: cn-beijing


gracefulShutdown:
  timeoutSeconds: 30

log:
  level: info