env: dev
port: 8080

postgres:
  dbname: lumino_dev
  host: 127.0.0.1
  port: 5433
  user: postgres
  passwd: 6666
  maxOpenConns: 50


oss:
  bucket: lumino-dev
  accessKey: LTAI5tFG9hdLbBgQdkqAzkYx
  secretKey: 48IjsI6afJqmlUkbUtFPWPJ84IGqEA
  region: cn-beijing
  profilePhotoDir: icon/profile_photo/

gracefulShutdown:
  timeoutSeconds: 30

log:
  level: info