// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/account": {
            "get": {
                "tags": [
                    "账户"
                ],
                "summary": "获取账户",
                "parameters": [
                    {
                        "type": "number",
                        "description": "账户余额",
                        "name": "balance",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-03-26T00:00:00Z",
                        "description": "DeletedAt 删除时间",
                        "name": "deleted_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户描述",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户图标",
                        "name": "icon",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "主键id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "账户类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间",
                        "name": "updated_at",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "创建人",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账户结果",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Account"
                            }
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "账户"
                ],
                "summary": "修改账户",
                "parameters": [
                    {
                        "type": "number",
                        "description": "账户余额",
                        "name": "balance",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-03-26T00:00:00Z",
                        "description": "DeletedAt 删除时间",
                        "name": "deleted_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户描述",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户图标",
                        "name": "icon",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "主键id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "账户类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间",
                        "name": "updated_at",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "创建人",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "账户"
                ],
                "summary": "注册账户",
                "parameters": [
                    {
                        "type": "number",
                        "description": "账户余额",
                        "name": "balance",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-03-26T00:00:00Z",
                        "description": "DeletedAt 删除时间",
                        "name": "deleted_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户描述",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户图标",
                        "name": "icon",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "主键id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "账户类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间",
                        "name": "updated_at",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "创建人",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "账户"
                ],
                "summary": "删除账户",
                "parameters": [
                    {
                        "type": "number",
                        "description": "账户余额",
                        "name": "balance",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间",
                        "name": "created_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2025-03-26T00:00:00Z",
                        "description": "DeletedAt 删除时间",
                        "name": "deleted_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户描述",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户图标",
                        "name": "icon",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "主键id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账户名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "账户类型",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间",
                        "name": "updated_at",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "创建人",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/account-book": {
            "get": {
                "tags": [
                    "账本"
                ],
                "summary": "获取账本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "排序模式  0: 创建时间升序，1:创建时间降序",
                        "name": "sort_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账本结果",
                        "schema": {
                            "$ref": "#/definitions/model.AccountBookResp"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "账本"
                ],
                "summary": "修改账本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账本id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账本名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "账本用户列表",
                        "name": "user_ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账本结果",
                        "schema": {
                            "$ref": "#/definitions/model.AccountBook"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "账本"
                ],
                "summary": "注册账本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "创建人",
                        "name": "creator_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账本名称",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "账本用户列表",
                        "name": "user_ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册结果",
                        "schema": {
                            "$ref": "#/definitions/model.AccountBook"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "账本"
                ],
                "summary": "删除账本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账本id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/account-book/:id": {
            "get": {
                "tags": [
                    "账本"
                ],
                "summary": "获取账本",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint",
                        "description": "账本id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账本结果",
                        "schema": {
                            "$ref": "#/definitions/model.AccountBookResp"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/account-book/merge": {
            "post": {
                "tags": [
                    "账本"
                ],
                "summary": "合并账本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "创建人(只能合并自己创建的账本)",
                        "name": "creator_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "合并的账本id  A",
                        "name": "merge_account_book_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "被合并的账本id B -\u003e A，B的记录全部合入到A",
                        "name": "merged_account_book_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账本结果",
                        "schema": {
                            "$ref": "#/definitions/model.AccountBookResp"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/category": {
            "get": {
                "tags": [
                    "图标"
                ],
                "summary": "获取图标",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID 图标id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图标结果",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Category"
                            }
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "图标"
                ],
                "summary": "修改图标信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID 图标id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分类名称的中文示意",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图标结果",
                        "schema": {
                            "$ref": "#/definitions/model.Category"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "图标"
                ],
                "summary": "注册图标",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类名称的中文示意",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "分类图标文件",
                        "name": "icon_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "图标信息",
                        "schema": {
                            "$ref": "#/definitions/model.Category"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "图标"
                ],
                "summary": "删除图标",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID 图标id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/category/icon-image": {
            "put": {
                "tags": [
                    "图标"
                ],
                "summary": "修改图标文件",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID 图标id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "分类图标文件",
                        "name": "icon_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/friend": {
            "delete": {
                "tags": [
                    "朋友"
                ],
                "summary": "删除朋友",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "被邀请人",
                        "name": "invitee",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "邀请人",
                        "name": "inviter",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/friend/invite": {
            "post": {
                "tags": [
                    "朋友"
                ],
                "summary": "邀请朋友",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "被邀请人",
                        "name": "invitee",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "邀请人",
                        "name": "inviter",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/health": {
            "get": {
                "tags": [
                    "健康检查"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/transaction": {
            "get": {
                "tags": [
                    "交易记录"
                ],
                "summary": "获取交易记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "对应的账本id",
                        "name": "account_book_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "起始时间",
                        "name": "begin_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "交易id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "交易记录",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Transaction"
                            }
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "交易记录"
                ],
                "summary": "修改交易记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "对应的账本id",
                        "name": "account_book_id",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "交易数额,数值需要\u003e0",
                        "name": "amount",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "关联消费场景分类ID",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "交易日期",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "注释",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "交易记录id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "付款人id",
                        "name": "pay_user_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "RelatedUserIDs 涉及那些人",
                        "name": "related_user_ids",
                        "in": "query"
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "description": "类型:收入/支出,交易类型必须是0或者1",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "交易信息",
                        "schema": {
                            "$ref": "#/definitions/model.Transaction"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "交易记录"
                ],
                "summary": "注册交易记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "对应的账本id",
                        "name": "account_book_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "交易数额",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "关联消费场景分类ID",
                        "name": "category_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "创建人id",
                        "name": "creator_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "注释",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "付款人id",
                        "name": "pay_user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minItems": 1,
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "RelatedUserIDs 涉及那些人",
                        "name": "related_user_ids",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            1,
                            2
                        ],
                        "type": "integer",
                        "description": "类型:收入/支出",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "交易记录",
                        "schema": {
                            "$ref": "#/definitions/model.Transaction"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "交易记录"
                ],
                "summary": "删除交易记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "交易记录id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "get": {
                "tags": [
                    "用户"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id(id,昵称，手机号至少一个)",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "账号名称，昵称，全局唯一",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone_number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户结果",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "用户"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "type": "number",
                        "description": "余额",
                        "name": "balance",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "默认账本id",
                        "name": "default_account_book_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "朋友列表",
                        "name": "friend",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账号名称，昵称，全局唯一",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone_number",
                        "in": "query"
                    },
                    {
                        "type": "object",
                        "description": "余额详情",
                        "name": "balance_detail",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户修改后结果",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "用户"
                ],
                "summary": "注册用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号名称，昵称，全局唯一",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone_number",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户头像",
                        "name": "icon_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册结果",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "用户"
                ],
                "summary": "删除用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile-photo": {
            "put": {
                "tags": [
                    "用户"
                ],
                "summary": "修改用户头像",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户头像",
                        "name": "icon_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "请求体异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    },
                    "500": {
                        "description": "服务端异常",
                        "schema": {
                            "$ref": "#/definitions/http_error_code.AppError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http_error_code.AppError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP状态码",
                    "type": "integer"
                },
                "detail": {
                    "description": "调试细节",
                    "type": "string"
                },
                "message": {
                    "description": "用户友好消息",
                    "type": "string"
                },
                "service": {
                    "description": "服务名称",
                    "type": "string"
                },
                "type": {
                    "description": "错误类型",
                    "type": "string"
                }
            }
        },
        "model.Account": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "账户余额",
                    "type": "number"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "DeletedAt 删除时间",
                    "type": "string",
                    "example": "2025-03-26T00:00:00Z"
                },
                "description": {
                    "description": "账户描述",
                    "type": "string"
                },
                "icon": {
                    "description": "账户图标",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "name": {
                    "description": "账户名称",
                    "type": "string"
                },
                "type": {
                    "description": "账户类型",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "user_id": {
                    "description": "创建人",
                    "type": "integer"
                }
            }
        },
        "model.AccountBook": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator_id": {
                    "description": "创建人,不允许修改",
                    "type": "integer"
                },
                "deleted_at": {
                    "description": "DeletedAt 删除时间",
                    "type": "string",
                    "example": "2025-03-26T00:00:00Z"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "income": {
                    "description": "账本收入",
                    "type": "number"
                },
                "name": {
                    "description": "账本名称",
                    "type": "string"
                },
                "spending": {
                    "description": "账本花费",
                    "type": "number"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "user_ids": {
                    "description": "账本用户列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "model.AccountBookResp": {
            "type": "object",
            "properties": {
                "account_books": {
                    "description": "账本列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AccountBook"
                    }
                },
                "default_account_book_id": {
                    "description": "默认版本id",
                    "type": "integer"
                },
                "users": {
                    "description": "涉及的用户信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                }
            }
        },
        "model.BalanceDetail": {
            "type": "object",
            "additionalProperties": {
                "type": "number"
            }
        },
        "model.Category": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "DeletedAt 删除时间",
                    "type": "string",
                    "example": "2025-03-26T00:00:00Z"
                },
                "icon_url": {
                    "description": "类别图标的本地地址",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "name": {
                    "description": "分类名称的中文示意",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "model.Transaction": {
            "type": "object",
            "properties": {
                "account_book_id": {
                    "description": "对应的账本id",
                    "type": "integer"
                },
                "amount": {
                    "description": "交易数额",
                    "type": "number"
                },
                "category_id": {
                    "description": "关联消费场景分类ID",
                    "type": "integer"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator_id": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "date": {
                    "description": "日期",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "DeletedAt 删除时间",
                    "type": "string",
                    "example": "2025-03-26T00:00:00Z"
                },
                "description": {
                    "description": "注释",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "pay_user_id": {
                    "description": "付款人id",
                    "type": "integer"
                },
                "related_user_ids": {
                    "description": "RelatedUserIDs 涉及那些人",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "type": {
                    "description": "类型:收入/支出",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "balance": {
                    "description": "余额",
                    "type": "number"
                },
                "balance_detail": {
                    "description": "BalanceDetail 余额详情\n@swagger:type object\n@additionalProperties type=number format=double\n@example {\"temperature\":36.5,\"humidity\":0.42}",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.BalanceDetail"
                        }
                    ]
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "default_account_book_id": {
                    "description": "默认账本id",
                    "type": "integer"
                },
                "deleted_at": {
                    "description": "DeletedAt 删除时间",
                    "type": "string",
                    "example": "2025-03-26T00:00:00Z"
                },
                "friend": {
                    "description": "朋友列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "icon_url": {
                    "description": "用户头像的对象存储地址",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "name": {
                    "description": "账号名称，昵称，全局唯一",
                    "type": "string"
                },
                "phone_number": {
                    "description": "手机号",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Lumino",
	Description:      "lumino 记账本服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
