basePath: /api/v1
host: 182.92.152.108:8080
info:
  contact: {}
  description: lumino 记账本服务
  title: Lumino
  version: "1.0"
paths:
  /api/v1/register:
    post:
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: 注册新的图标类型
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
